import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "../components/nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Showboxd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} font-sans h-full antialiased scroll-smooth`}>
      <body className="min-h-full flex flex-col pt-14">
        <Nav />
        {children}
        <footer className="border-t border-white/10 bg-neutral-900/20 py-12 text-center text-white/40 text-sm">
          <p>&copy; 2026 Showboxd. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
